version: "3"

services:
  xk:
    image: exekube/exekube:0.3.1-google
    working_dir: /project
    environment:
      USER: root
      ENV: ${ENV:?err}
      ORGANIZATION_ID:
      BILLING_ID:
      TF_INPUT: "0"
      TF_LOG:
      TF_VAR_project_id: ${ENV}-demo-apps-296e23
      TF_VAR_serviceaccount_key: /project/live/${ENV}/secrets/kube-system/owner.json
      TF_VAR_default_dir: /project/live/${ENV}/k8s
      TF_VAR_secrets_dir: /project/live/${ENV}/secrets
      TF_VAR_keyring_name: keyring
    ports:
      - 8001:8001
    volumes:
      - ../exekube/exekube/modules:/exekube-modules

      - .:/project
      - ./.config/${ENV}/helm:/root/.helm
      - ./.config/${ENV}/terragrunt:/root/.terragrunt
      - ./.config/${ENV}/gcloud:/root/.config/gcloud
      - ./.config/${ENV}/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"

  # zap:
  #   image: owasp/zap2docker-stable:2.7.0
  #   ports:
  #     - 8080:8080
  #     - 8090:8090
  #   command: zap-webswing.sh
