
{{- if .Values.ingress.enabled -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fronted-ingress
  labels:
    app: guestbook
    tier: frontend
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
    {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end -}}
