apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: apps-ingress-tls
  namespace: default
spec:
  secretName: apps-ingress-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - "*.dev.apps.exekube.us"
  acme:
    config:
    - dns01:
        provider: cert-manager-clouddns
      domains:
        - "*.dev.apps.exekube.us"
