# List namespaces to create
namespaces:
  - name: monitoring
    secure: false
    labels:
      name: monitoring
  - name: heptio-ark
    secure: false
    labels:
      name: heptio-ark
      app: ark

# Assign users as cluster-admins
clusterAdmins:
  create: false
  users: []

# List roles to limit things you can view / modify with the dashboard
# By default, you only get the "view" role
# TODO We should move dashboard deployment from GKE to Helm chart
dashboardPermissions:
  create: true
  clusterRoles:
    # - view
    # - secret-lister
    # - cluster-object-viewer
    - cluster-admin
