# Default values for nginx-react.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
resources: {}

image:
  repository: ilyasotkov/forms-app
  tag: latest
  pullPolicy: IfNotPresent

serviceType: ClusterIP
servicePort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"

  hosts:
    - ${domain_name}
  tls:
    - secretName: apps-ingress-tls
      hosts:
        - ${domain_name}
