image: concourse/concourse

## Concourse image version.
## ref: https://hub.docker.com/r/concourse/concourse/tags/
##
imageTag: "3.13.0"

concourse:
  basicAuth:
    enabled: true
  externalURL: https://${domain_name}
  githubAuth:
    enabled: true
    user: ilyasotkov

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - ${domain_name}
    tls:
      - secretName: apps-ingress-tls
        hosts:
          - ${domain_name}

postgresql:
  postgresDatabase: concourse

rbac:
  create: true

credentialManager:
  kubernetes:
    enabled: true
    namespacePrefix: "concourse-"
    keepNamespaces: false
    teams:
      - main

  vault:
    enabled: false
    # enabled: true
    # url: https://vault-vault:8200
    # pathPrefix: "/concourse"
    # authBackend: ""
    # caCert: true

secrets:
  create: false
